

services:
  backend:
    build: ./backend
    container_name: sgas_backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - sgas_network

  db:
    image: postgres:15
    container_name: sgas_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app123
      POSTGRES_DB: sgas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sgas_network

  redis:
    image: redis:7
    container_name: sgas_redis
    networks:
      - sgas_network

networks:
  sgas_network:
    driver: bridge

volumes:
  postgres_data:
